M: 2012-03-20 13:21:00,371 ERROR main SaveLoadCache:writeFile:42 - IO Exception. 
java.io.FileNotFoundException: resources/test0.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:36)
	at com.sysgears.calculatorserver.kernell.cache.UTestSaveLoadCache.testWriteFile(UTestSaveLoadCache.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
M: 2012-03-20 13:21:00,510 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 15:37:31,963 ERROR main SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/test0.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.UTestSaveLoadCache.testWriteFile(UTestSaveLoadCache.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
M: 2012-03-21 15:37:32,431 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 15:43:21,931 ERROR main SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/test0.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.UTestSaveLoadCache.testWriteFile(UTestSaveLoadCache.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
M: 2012-03-21 15:44:00,263 ERROR main SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/test0.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.UTestSaveLoadCache.testWriteFile(UTestSaveLoadCache.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
M: 2012-03-21 15:46:46,088 ERROR main SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/test0.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.UTestSaveLoadCache.testWriteFile(UTestSaveLoadCache.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
M: 2012-03-21 16:09:24,577 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 16:15:21,457 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 16:36:17,057 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 16:48:21,993 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-21 17:43:29,620 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:32:09,744 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:40:29,564 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:43:23,387 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:45:24,239 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:48:04,475 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2012-03-22 09:49:01,199 ERROR main CalculationThread:getAndProcessStatement:239 - Statement error.
M: 2013-04-20 17:20:29,561 ERROR pool-1-thread-1 SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/default.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:20:29,565 ERROR pool-1-thread-1 CalculationThread:getAndProcessStatement:259 - Exception.
java.lang.NullPointerException
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:50)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:25:33,688 ERROR pool-1-thread-1 SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/default.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:25:33,691 ERROR pool-1-thread-1 CalculationThread:getAndProcessStatement:259 - Exception.
java.lang.NullPointerException
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:50)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:26:20,005 ERROR Thread-0 Server:run:100 - Error in accepting connection.
M: 2013-04-20 17:26:20,006 ERROR Thread-0 Server:run:110 - Socket closing error.
M: 2013-04-20 17:26:51,964 ERROR pool-1-thread-1 SaveLoadCache:writeFile:45 - IO Exception. 
java.io.FileNotFoundException: resources/default.cache (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:165)
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:39)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:26:51,967 ERROR pool-1-thread-1 CalculationThread:getAndProcessStatement:259 - Exception.
java.lang.NullPointerException
	at com.sysgears.calculatorserver.kernell.cache.SaveLoadCache.writeFile(SaveLoadCache.java:50)
	at com.sysgears.calculatorserver.kernell.cache.Cache.saveCache(Cache.java:148)
	at com.sysgears.calculatorserver.kernell.cache.Cache.addToCache(Cache.java:100)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:52)
	at com.sysgears.calculatorserver.kernell.calculation.Calculator.calculate(Calculator.java:71)
	at com.sysgears.calculatorserver.kernell.calculation.AnswerSearcher.getAnswer(AnswerSearcher.java:50)
	at com.sysgears.calculatorserver.server.CalculationThread.getAndProcessStatement(CalculationThread.java:224)
	at com.sysgears.calculatorserver.server.CalculationThread.run(CalculationThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
M: 2013-04-20 17:28:24,633 ERROR Thread-0 Server:run:100 - Error in accepting connection.
M: 2013-04-20 17:28:24,634 ERROR Thread-0 Server:run:110 - Socket closing error.
